
apiVersion: apps/v1
kind: Deployment
metadata:
  name: invia-deployment
spec:
  selector:
    matchLabels:
      app: invia
  replicas: 3
  template:
    metadata:
      labels:
        app: invia
    spec:
      containers:
        - name: invia
          image: varadharajaan/invia:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: invia
  labels:
    app: invia
spec:
  selector:
    app: invia
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  type: LoadBalancer
